brew 'ag'
brew 'bash'
brew 'bash-completion'
brew 'coreutils'
brew 'direnv'
brew 'findutils'
brew 'foremost'
brew 'git'
brew 'gnu-sed', args: ['default-names']
brew 'hashpump'
brew 'heroku'
brew 'grep'
brew 'screen'
brew 'libxml2'
brew 'libxslt'
brew 'lynx'
brew 'moreutils'
brew 'mysql'
brew 'narwhal'
brew 'nmap'
brew 'p7zip'
brew 'pigz'
brew 'postgresql'
brew 'pv'
brew 'qt55'
brew 'rbenv'
brew 'redis'
brew 'rename'
brew 'rhino'
brew 'ruby-build'
brew 'tree'
brew 'ucspi-tcp'
brew 'vim', args: ['override-system-vi']
brew 'webkit2png'
brew 'wget', args: ['enable-iri']
